services:
  stats-server:
    image: stats-image
    container_name: stats-server
    ports:
      - "9090:9090"
    build:
      context: ./ewm-stats-service/server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats-db
      - SPRING_DATASOURCE_USERNAME=ewm-admin
      - SPRING_DATASOURCE_PASSWORD=hehehe
    depends_on:
      - stats-db

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=hehehe
      - POSTGRES_USER=ewm-admin
      - POSTGRES_DB=ewm-stats-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    image: ewm-image
    container_name: ewm-service
    ports:
      - "8080:8080"
    build:
      context: ./ewm-main-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=ewm-admin
      - SPRING_DATASOURCE_PASSWORD=hehehe
    depends_on:
      - ewm-db
      - stats-server

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_PASSWORD=hehehe
      - POSTGRES_USER=ewm-admin
      - POSTGRES_DB=ewm-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10